In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sqlalchemy import create_engine, text
from sklearn.cluster import KMeans


DB_URI = "mysql+pymysql://root:@127.0.0.1:3306/trenparpol"

engine = create_engine(DB_URI)

print("📊 Mengambil data rekap suara 2024...")

df = pd.read_sql("SELECT id_partai, total_suara FROM rekap_suara_2024", engine)

print("Data yang akan di-clustering:")
display(df)

X = df[['total_suara']]

kmeans = KMeans(n_clusters=3, random_state=42, n_init='auto')
df['cluster'] = kmeans.fit_predict(X)

centroids = kmeans.cluster_centers_

df['nilai_centroid'] = df['cluster'].map({i: centroids[i][0] for i in range(3)})

df['jarak_centroid'] = abs(df['total_suara'] - df['nilai_centroid'])

sorted_centroids = np.sort(centroids.flatten())

kategori_map = {
    np.where(centroids.flatten() == sorted_centroids[0])[0][0]: 'Rendah',
    np.where(centroids.flatten() == sorted_centroids[1])[0][0]: 'Sedang',
    np.where(centroids.flatten() == sorted_centroids[2])[0][0]: 'Tinggi'
}

df['kategori_cluster'] = df['cluster'].map(kategori_map)


print("\n HASIL CLUSTERING K-MEANS 2024:")
df_sorted = df.sort_values(by='total_suara', ascending=False)
display(df_sorted)

print("\n💾 Menyimpan hasil ke tabel 'hasil_cluster_2024'...")

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE hasil_cluster_2024"))

df.to_sql('hasil_cluster_2024', engine, if_exists='append', index=False)

print("Data clustering 2024 berhasil disimpan.")

📊 Mengambil data rekap suara 2024...

Data yang akan di-clustering:

    id_partai  total_suara
0           4        53973
1          12        51898
2           8        38136
3           2        36607
4           1        35844
5           3        35118
6          14        33917
7           5        19385
8          10        11593
9          20         9554
10         11         7125
11         18         6558
12         15         2940
13         17         2539
14          9         1650
15         19         1096
16          6          622
17         13          600

 HASIL CLUSTERING K-MEANS 2024:

,id_partai,total_suara,cluster,nilai_centroid,jarak_centroid,kategori_cluster
0,4,53973,2,52935.500000,1037.500000,Tinggi
1,12,51898,2,52935.500000,1037.500000,Tinggi
2,8,38136,0,33167.833333,4968.166667,Sedang
3,2,36607,0,33167.833333,3439.166667,Sedang
4,1,35844,0,33167.833333,2676.166667,Sedang
5,3,35118,0,33167.833333,1950.166667,Sedang
6,14,33917,0,33167.833333,749.166667,Sedang
7,5,19385,0,33167.833333,13782.833333,Sedang
8,10,11593,1,4427.700000,7165.300000,Rendah
9,20,9554,1,4427.700000,5126.300000,Rendah
10,11,7125,1,4427.700000,2697.300000,Rendah
11,18,6558,1,4427.700000,2130.300000,Rendah
12,15,2940,1,4427.700000,1487.700000,Rendah
13,17,2539,1,4427.700000,1888.700000,Rendah
14,9,1650,1,4427.700000,2777.700000,Rendah
15,19,1096,1,4427.700000,3331.700000,Rendah
16,6,622,1,4427.700000,3805.700000,Rendah
17,13,600,1,4427.700000,3827.700000,Rendah

💾 Menyimpan hasil ke tabel 'hasil_cluster_2024'...
Data clustering 2024 berhasil disimpan.

In [11]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
from sklearn.cluster import KMeans

DB_URI = "mysql+pymysql://root:@127.0.0.1:3306/trenparpol"
engine = create_engine(DB_URI)

print("📊 Mengambil data rekap suara 2019...")

df_2019 = pd.read_sql("SELECT id_partai, total_suara FROM rekap_suara_2019", engine)

print("Data yang akan di-clustering:")
display(df_2019)

X_2019 = df_2019[['total_suara']]

kmeans_2019 = KMeans(n_clusters=3, random_state=42, n_init='auto')
df_2019['cluster'] = kmeans_2019.fit_predict(X_2019)


centroids_2019 = kmeans_2019.cluster_centers_
df_2019['nilai_centroid'] = df_2019['cluster'].map({i: centroids_2019[i][0] for i in range(3)})
df_2019['jarak_centroid'] = abs(df_2019['total_suara'] - df_2019['nilai_centroid'])


sorted_centroids_2019 = np.sort(centroids_2019.flatten())

kategori_map_2019 = {
    np.where(centroids_2019.flatten() == sorted_centroids_2019[0])[0][0]: 'Rendah',
    np.where(centroids_2019.flatten() == sorted_centroids_2019[1])[0][0]: 'Sedang',
    np.where(centroids_2019.flatten() == sorted_centroids_2019[2])[0][0]: 'Tinggi'
}

df_2019['kategori_cluster'] = df_2019['cluster'].map(kategori_map_2019)

print("\n HASIL CLUSTERING K-MEANS 2019:")
df_2019_sorted = df_2019.sort_values(by='total_suara', ascending=False)
display(df_2019_sorted)

print("\n💾 Menyimpan hasil ke tabel 'hasil_cluster_2019'...")

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE hasil_cluster_2019"))

df_2019.to_sql('hasil_cluster_2019', engine, if_exists='append', index=False)

print("Data clustering 2019 berhasil disimpan.")

📊 Mengambil data rekap suara 2019...
Data yang akan di-clustering:

    id_partai  total_suara
0          12        59984
1           2        43135
2           4        38095
3           3        37674
4           8        35786
5           1        33327
6          14        20979
7          10        17317
8           5        15491
9           9        10596
10         13         9299
11         15         6330
12          7         5051
13         11         3067
14          6         1162
15         16          286

 HASIL CLUSTERING K-MEANS 2019:

,id_partai,total_suara,cluster,nilai_centroid,jarak_centroid,kategori_cluster
0,12,59984,2,59984.0,0.0,Tinggi
1,2,43135,0,37603.4,5531.6,Sedang
2,4,38095,0,37603.4,491.6,Sedang
3,3,37674,0,37603.4,70.6,Sedang
4,8,35786,0,37603.4,1817.4,Sedang
5,1,33327,0,37603.4,4276.4,Sedang
6,14,20979,1,8957.8,12021.2,Rendah
7,10,17317,1,8957.8,8359.2,Rendah
8,5,15491,1,8957.8,6533.2,Rendah
9,9,10596,1,8957.8,1638.2,Rendah
10,13,9299,1,8957.8,341.2,Rendah
11,15,6330,1,8957.8,2627.8,Rendah
12,7,5051,1,8957.8,3906.8,Rendah
13,11,3067,1,8957.8,5890.8,Rendah
14,6,1162,1,8957.8,7795.8,Rendah
15,16,286,1,8957.8,8671.8,Rendah

💾 Menyimpan hasil ke tabel 'hasil_cluster_2019'...
Data clustering 2019 berhasil disimpan.

In [12]:
print("Mengecek perbedaan partai 2019 dan 2024...")

partai_2019 = set(df_2019['id_partai'])
partai_2024 = set(df['id_partai'])

hanya_2019 = sorted(partai_2019 - partai_2024)
hanya_2024 = sorted(partai_2024 - partai_2019)
ada_keduanya = sorted(partai_2019 & partai_2024)

print("\nPartai yang ada di kedua periode:")
print(ada_keduanya)

print("\nPartai yang hanya ada di 2019:")
print(hanya_2019)

print("\nPartai yang hanya ada di 2024:")
print(hanya_2024)

print("\nJumlah:")
print("Ada di kedua periode :", len(ada_keduanya))
print("Hanya 2019          :", len(hanya_2019))
print("Hanya 2024          :", len(hanya_2024))

Mengecek perbedaan partai 2019 dan 2024...

Partai yang ada di kedua periode:
[1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15]

Partai yang hanya ada di 2019:
[7, 16]

Partai yang hanya ada di 2024:
[17, 18, 19, 20]

Jumlah:
Ada di kedua periode : 14
Hanya 2019          : 2
Hanya 2024          : 4

In [13]:
print("Membuat perbandingan suara 2019 dan 2024...")

perbandingan = pd.merge(
    df_2019[['id_partai', 'total_suara']],
    df[['id_partai', 'total_suara']],
    on='id_partai',
    how='inner',
    suffixes=('_2019', '_2024')
)

perbandingan['selisih_suara'] = (
    perbandingan['total_suara_2024']
    - perbandingan['total_suara_2019']
)

perbandingan['persentase_perubahan'] = (
    perbandingan['selisih_suara']
    / perbandingan['total_suara_2019']
    * 100
)

perbandingan = perbandingan.sort_values(
    by='total_suara_2024',
    ascending=False
)

print("\nHASIL PERBANDINGAN 14 PARTAI:")
display(perbandingan)

Membuat perbandingan suara 2019 dan 2024...

HASIL PERBANDINGAN 14 PARTAI:

,id_partai,total_suara_2019,total_suara_2024,selisih_suara,persentase_perubahan
2,4,38095,53973,15878,41.680011
0,12,59984,51898,-8086,-13.480261
4,8,35786,38136,2350,6.566814
1,2,43135,36607,-6528,-15.133882
5,1,33327,35844,2517,7.552435
3,3,37674,35118,-2556,-6.784520
6,14,20979,33917,12938,61.671195
8,5,15491,19385,3894,25.137176
7,10,17317,11593,-5724,-33.054224
12,11,3067,7125,4058,132.311705
11,15,6330,2940,-3390,-53.554502
9,9,10596,1650,-8946,-84.428086
13,6,1162,622,-540,-46.471601
10,13,9299,600,-8699,-93.547693

In [15]:
print("Menggabungkan hasil clustering 2019 dan 2024...")

cluster_2019 = df_2019[
    ['id_partai', 'cluster', 'kategori_cluster']
].rename(columns={
    'cluster': 'cluster_2019',
    'kategori_cluster': 'kategori_cluster_2019'
})

cluster_2024 = df[
    ['id_partai', 'cluster', 'kategori_cluster']
].copy()

cluster_2024 = cluster_2024.rename(columns={
    'cluster': 'cluster_2024',
    'kategori_cluster': 'kategori_cluster_2024'
})

perbandingan_cluster = perbandingan.merge(
    cluster_2019,
    on='id_partai',
    how='left'
)

perbandingan_cluster = perbandingan_cluster.merge(
    cluster_2024,
    on='id_partai',
    how='left'
)

print("\nHASIL PERBANDINGAN + CLUSTER:")
display(perbandingan_cluster)

Menggabungkan hasil clustering 2019 dan 2024...

HASIL PERBANDINGAN + CLUSTER:

,id_partai,total_suara_2019,total_suara_2024,selisih_suara,persentase_perubahan,cluster_2019,kategori_cluster_2019,cluster_2024,kategori_cluster_2024
0,4,38095,53973,15878,41.680011,0,Sedang,2,Tinggi
1,12,59984,51898,-8086,-13.480261,2,Tinggi,2,Tinggi
2,8,35786,38136,2350,6.566814,0,Sedang,0,Sedang
3,2,43135,36607,-6528,-15.133882,0,Sedang,0,Sedang
4,1,33327,35844,2517,7.552435,0,Sedang,0,Sedang
5,3,37674,35118,-2556,-6.784520,0,Sedang,0,Sedang
6,14,20979,33917,12938,61.671195,1,Rendah,0,Sedang
7,5,15491,19385,3894,25.137176,1,Rendah,0,Sedang
8,10,17317,11593,-5724,-33.054224,1,Rendah,1,Rendah
9,11,3067,7125,4058,132.311705,1,Rendah,1,Rendah
10,15,6330,2940,-3390,-53.554502,1,Rendah,1,Rendah
11,9,10596,1650,-8946,-84.428086,1,Rendah,1,Rendah
12,6,1162,622,-540,-46.471601,1,Rendah,1,Rendah
13,13,9299,600,-8699,-93.547693,1,Rendah,1,Rendah

In [16]:
print("Menentukan perubahan cluster 2019 → 2024...")

def status_cluster(row):
    if row['kategori_cluster_2019'] == row['kategori_cluster_2024']:
        return 'Tetap'
    else:
        return (
            row['kategori_cluster_2019']
            + ' → '
            + row['kategori_cluster_2024']
        )

perbandingan_cluster['perubahan_cluster'] = (
    perbandingan_cluster.apply(status_cluster, axis=1)
)

print("\nHASIL AKHIR PERBANDINGAN CLUSTER:")
display(perbandingan_cluster)

Menentukan perubahan cluster 2019 → 2024...

HASIL AKHIR PERBANDINGAN CLUSTER:

,id_partai,total_suara_2019,total_suara_2024,selisih_suara,persentase_perubahan,cluster_2019,kategori_cluster_2019,cluster_2024,kategori_cluster_2024,perubahan_cluster
0,4,38095,53973,15878,41.680011,0,Sedang,2,Tinggi,Sedang → Tinggi
1,12,59984,51898,-8086,-13.480261,2,Tinggi,2,Tinggi,Tetap
2,8,35786,38136,2350,6.566814,0,Sedang,0,Sedang,Tetap
3,2,43135,36607,-6528,-15.133882,0,Sedang,0,Sedang,Tetap
4,1,33327,35844,2517,7.552435,0,Sedang,0,Sedang,Tetap
5,3,37674,35118,-2556,-6.784520,0,Sedang,0,Sedang,Tetap
6,14,20979,33917,12938,61.671195,1,Rendah,0,Sedang,Rendah → Sedang
7,5,15491,19385,3894,25.137176,1,Rendah,0,Sedang,Rendah → Sedang
8,10,17317,11593,-5724,-33.054224,1,Rendah,1,Rendah,Tetap
9,11,3067,7125,4058,132.311705,1,Rendah,1,Rendah,Tetap
10,15,6330,2940,-3390,-53.554502,1,Rendah,1,Rendah,Tetap
11,9,10596,1650,-8946,-84.428086,1,Rendah,1,Rendah,Tetap
12,6,1162,622,-540,-46.471601,1,Rendah,1,Rendah,Tetap
13,13,9299,600,-8699,-93.547693,1,Rendah,1,Rendah,Tetap